# Generated by Django 4.1.6 on 2023-02-21 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='budget',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='category',
            name='budget',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.category'),
        ),
        migrations.AlterField(
            model_name='report',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.method'),
        ),
        migrations.DeleteModel(
            name='Subcategory',
        ),
    ]
