# Generated by Django 4.1.6 on 2023-02-27 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_alter_report_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
