# Generated by Django 4.1.6 on 2023-02-27 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_alter_report_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ('date',)},
        ),
    ]
