# Generated by Django 4.1.6 on 2023-02-23 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='account',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to='server.account'),
        ),
        migrations.AlterField(
            model_name='account',
            name='budget',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='category',
            name='budget',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='category',
            field=models.ForeignKey(default=17, on_delete=django.db.models.deletion.CASCADE, to='server.category'),
        ),
        migrations.AlterField(
            model_name='report',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.method'),
        ),
    ]
