# Generated by Django 4.1.6 on 2023-02-23 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_report_account_alter_account_budget_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='author',
        ),
        migrations.AlterField(
            model_name='report',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.account'),
        ),
        migrations.AlterField(
            model_name='report',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.category'),
        ),
    ]
